### ISSUE TITLE
create app in __init__.py

### ISSUE THREAD

**Issue by copdips** [jelmerdejong/flask-app-blueprint#44]
Hi,
I would like to know if it is good to create flask app in project root `__init__.py` file, as each time we import something from project.x.x, there would be a flask app created.

https://github.com/jelmerdejong/flask-app-blueprint/blob/1f3b887fadb7cacbd97557e0836f1d9756dd82e6/project/__init__.py#L12

**Comment by jelmerdejong** [comment]
Hi, please refer to the Flask website and Flask documentation for general Flask questions: https://palletsprojects.com/p/flask/
