### ISSUE TITLE
In Windows

### ISSUE THREAD

**Issue by luigigarcia19** [jelmerdejong/flask-app-blueprint#49]
He bajado el repositorio y me ha tomado algo de tiempo poder correrlo jeje.

Dejo aquí si a alguien le sirve. Soy nuevo en python, vengo de php :), y este trabajo q han realizado es excelente, es de gran ayuda.

Estos datos son los que apunté para que la app pueda correr:

_actualizar las dependencias w10_

Lo q hizo esto fue actualizar todos recursos porq al principio no corría, antes de hacer esto también reemplazar todas == por >= de esa manera me aseguraba que las versiones sean las más recientes.

cffi>=1.15.0
pip install -r requirements.txt --upgrade

_También necesitaba instalar un recurso de vs_
[https://visualstudio.microsoft.com/es/visual-cpp-build-tools/](https://visualstudio.microsoft.com/es/visual-cpp-build-tools/)

Tambien declaré en la consola los siguientes parámetros antes escritos en el archivo **.flaskenv**

set FLASK_APP=project
set FLASK_ENV=development
set APP_SETTINGS="config.DevelopmentConfig"

Para darme cuenta de los errores q pude solucionar por tema de versiones agregué el siguiente archivo en la raíz

app.py
`from project import app`

De esta manera al correr app.py pude ver con detalle los problemas.

Al finalizar corrí el flask run y woala!!!!!

**Comment by jelmerdejong** [comment]
Hi! Feel free to open a Pull Request to improve the docs to make it easier to use on Windows.
