### ISSUE TITLE
can't open file 'manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hailyngx** [jelmerdejong/flask-app-blueprint#50]
Hi, I am new to web dev. Thank you so much for making this!

**Comment by dankstarr** [comment]
Same error
heroku run python manage.py db upgrade --app 
Running python manage.py db upgrade on ⬢ ... up, run.1467 (Free)
python: can't open file 'manage.py': [Errno 2] No such file or directory

**Comment by jelmerdejong** [comment]
You can now upgrade the database (locally and remote) by running `flask db upgrade` will update docs later.
