### ISSUE TITLE
 can't open file 'manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dankstarr** [jelmerdejong/flask-app-blueprint#51]
Everything works fine except the db
#heroku run python manage.py db upgrade --app
Running python manage.py db upgrade on ⬢ ... up, run.1467 (Free)
python: can't open file 'manage.py': [Errno 2] No such file or directory

Also mandrill doesn't work since Mailchimp took over

**Comment by jelmerdejong** [comment]
You can now update the database by running `flask db upgrade`
